# Generated by Django 5.0.6 on 2024-06-30 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="context",
            new_name="content",
        ),
    ]
